version: '2'
services:
  version:
    image: maven:3.3.9-jdk-8
    volumes:
      - ${HOME}/glytoucan/maven:/root/.m2
      - .:/workspace
      - /etc/localtime:/etc/localtime
      - ${SETTINGS_PATH}:/root/.m2/settings.xml
    working_dir: /workspace/
    command: mvn -N deploy
    network_mode: "host"
