version: '2'
services:
  java:
    image: maven:3.3.9-jdk-8
    ports:
     - 81:80
    volumes:
     - ${HOME}/glytoucan/java/tmp:/tmp
     - ${HOME}/glytoucan/maven:/root/.m2
     - ${HOME}/glytoucan/java/upload:/upload
     - /etc/localtime:/etc/localtime
     - ${PARENT_WORKSPACE}/${WORKSPACE}/docker-compose-glytoucan:/workspace
    working_dir: /workspace/rdf.glytoucan
    command: mvn -U -DskipTests=true -T 2C spring-boot:run
#env_file: glytoucan.env
    environment:
     - GOOGLE_OAUTH2_CLIENTID
     - GOOGLE_OAUTH2_CLIENTSECRET
     - SPRING_MAIL_USERNAME
     - SPRING_MAIL_PASSWORD
     - SPRING_TRIPLESTORE_PASSWORD
     - SPRING_TRIPLESTORE_URL
     - API_CONTRIBUTOR_ID
     - API_KEY
     - GTC_VERSION
     - sitemapHostname=http://beta.glytoucan.org
#  links:
#    - stanza:stanza.glytoucan.org
#    - api:test.api.glytoucan.org
#    - local:local.glytoucan.org
    restart: always
#volumes:
#  source:
#    external:
#      name: source.${GTC_VERSION}
