version: '2'
services:
  java:
    extends:
      file: docker-compose.java.yml
      service: java
    image: maven:3.3.9-jdk-8
    command: mvn -DskipTests=true clean package
    restart: never
  api:
    extends:
      file: docker-compose.api.yml
      service: api
    image: maven:3.3.9-jdk-8
    command: mvn -DskipTests=true clean package
    restart: never
  soap.api:
    extends:
      file: docker-compose.soap.api.yml
      service: soap.api
    image: maven:3.3.9-jdk-8
    command: mvn -DskipTests=true clean package
    restart: never
  data:
    build: docker-data
    image: glycoinfo.org:5000/glytoucan_data:v${GTC_VERSION}
    volumes:
      - ./rdf.glytoucan:/rdf.glytoucan
      - ./glytoucan-stanza:/glytoucan-stanza
      - ./glytoucan-js-stanza:/glytoucan-js-stanza
      - ./api:/api
      - ./soap.api:/soap.api
      - ./pom-site:/pom-site
    environment:
      - GTC_VERSION
    depends_on:
      - java
      - api
      - soap.api
