version: '2'
services:
  api:
    extends:
      file: docker-compose.api.yml
      service: api
  soap.api:
    extends:
      file: docker-compose.soap.api.yml
      service: soap.api
  client:
    image: maven:3.3.9-jdk-8
    volumes:
      - ${HOME}/glytoucan/maven:/root/.m2
      - ${PARENT_WORKSPACE}/${WORKSPACE}/docker-compose-glytoucan:/workspace
      - /etc/localtime:/etc/localtime
    working_dir: /workspace/client
    command: /workspace/wait/wait-for-it.sh soap.api:80 -- mvn deploy
    links:
      - api:test.api.glytoucan.org
      - soap.api:test.soap.api.glytoucan.org
    depends_on:
      - api
      - soap.api
