web:
  # https://bitbucket.org/aokinobu/docker-glytoucan.git
  build: docker-glytoucan
#  image: glytoucan-web
  ports:
   - "90:80"
  volumes:
   - /opt/glytoucan/apacherun:/var/run/apache2
   - /opt/glytoucan/apachelogs:/var/log/apache2
   - /etc/localtime:/etc/localtime
  links:
   - squid:rdf.glytoucan.org
#   - stanza:stanza.glytoucan.org
   - api:test.api.glytoucan.org
   - soap.api:soap.api.glytoucan.org
   - glycanbuilder:glycanbuilder.glytoucan.org
     #   - awstats:stats.glytoucan.org
  restart: always
squid:
  extends:
    file: docker-compose.squid.yml
    service: squid
  links:
    - java:rdf.glytoucan.org
java:
  extends:
    file: docker-compose.java.yml
    service: java
  links:
    - stanza:stanza.glytoucan.org
    - api:test.api.glytoucan.org
#    - local:local.glytoucan.org
  restart: always
#awstats:
#  build: ${WORKSPACE_PARENT}/${WORKSPACE}/docker-awstats
#  ports:
#  volumes:
#   - /opt/bluetree/apacherun:/var/run/apache2
#    - /opt/glytoucan/awstats/data:/var/lib/awstats
#    - /opt/glytoucan/apache/www:/var/www/html
#    - /opt/glytoucan/awstats/logs:/var/log
#   - /var/log:/var/log
#   - ${HOME}/${WORKSPACE}/docker-awstats/logs:/var/log/apache2
#    - /etc/localtime:/etc/localtime         
api:
  extends:
    file: docker-compose.api.yml
    service: api
soap.api:
  extends:
    file: docker-compose.soap.api.yml
    service: soap.api
glycanbuilder:
  extends:
    file: docker-compose.glycanbuilder.yml
    service: glycanbuilder
stanza:
  extends:
    file: docker-compose.stanza.yml
    service: stanza
  links:
    - api:rdf.glytoucan.org
