java:
# https://github.com/glytoucan/docker-rdf.glytoucan.git
  build: docker-rdf.glytoucan
  ports:
   - 81:80
  volumes:
   - /opt/glytoucan/java/tmp:/tmp
   - /opt/glytoucan/maven:/root/.m2
   - ./rdf.glytoucan:/workspace
   - /opt/glytoucan/java/upload:/upload
   - /etc/localtime:/etc/localtime
  working_dir: /workspace
#env_file: glytoucan.env
  environment:
   - HOSTNAME=rdf.glytoucan
#  links:
#    - stanza:stanza.glytoucan.org
#    - api:test.api.glytoucan.org
#    - local:local.glytoucan.org
  restart: always
