# This is a simple setup for apache, java, and stanza.  Substructure search should be possible, however GlycanBuilder (graphics search) will not.
# For graphics search, please use the default docker-compose.yml ()
version: '2'
services:
  web:
    extends:
      file: docker-compose.web.yml
      service: web
    links:
#     - api:test.api.glytoucan.org
     - js-stanza:js-stanza.glytoucan.org
     - java:squid.glytoucan.org
    restart: never
  java:
    extends:
      file: docker-compose.java.yml
      service: java
    links:
      - stanza:stanza.glytoucan.org
#      - api:test.api.glytoucan.org
    env_file:
      - ./mail.env
      - ./api.env
    environment:
      - SPRING_TRIPLESTORE_URL=jdbc:virtuoso://test.ts.glytoucan.org:1111
      - SPRING_TRIPLESTORE_PASSWORD=dba
      - GTC_VERSION=DEV_VERSION
      - GOOGLE_OAUTH2_CLIENTID=144546288829-o7vr36n5s7it71pi6tandfmsqteq38p3.apps.googleusercontent.com
      - GOOGLE_OAUTH2_CLIENTSECRET=Lpd2gIA6fRMgYuH3dhmrTx-O
      - ADMIN_URI=http://test.api.glytoucan.org/admin/
    restart: never
  stanza:
    extends:
      file: docker-compose.stanza.yml
      service: stanza
#    links:
#      - api:rdf.glytoucan.org
#  api:
#    extends:
#      file: docker-compose.api.yml
#      service: api
#    env_file:
#      - ./mail.env
#      - ./triplestore.env
#      - ./api.env
#    environment:
#      - SPRING_TRIPLESTORE_URL=jdbc:virtuoso://test.ts.glytoucan.org:1111
#      - SPRING_TRIPLESTORE_PASSWORD=dba
    restart: never
    # volumes_from:
    #   - bundle
  js-stanza:
    extends:
      file: docker-compose.js-stanza.yml
      service: js-stanza
    restart: never
  # bundle:
  #   image: debian
  #   command: echo bundle path holder
  #   volumes:
  #     - /bundle
