web:
  # https://bitbucket.org/aokinobu/docker-glytoucan.git
  build: docker-glytoucan
#  image: glytoucan-web
  ports:
   - "90:80"
  volumes:
   - /opt/glytoucan/apacherun:/var/run/apache2
   - /opt/glytoucan/apachelogs:/var/log/apache2
   - /etc/localtime:/etc/localtime
  links:
   - squid:rdf.glytoucan.org
   - stanza:stanza.glytoucan.org
   - api:test.api.glytoucan.org
   - soap.api:soap.api.glytoucan.org
   - glycanbuilder:glycanbuilder.glytoucan.org
     #   - awstats:stats.glytoucan.org
  restart: always
glycanbuilder:
  build: docker-glycanbuilder
  ports:
   - "8080:80"
  volumes:
   - /etc/localtime:/etc/localtime
  restart: always
squid:
  # https://github.com/glytoucan/docker-glyspacesquid.git
  build: docker-glyspacesquid
  ports:
   - "3180:80"
   - "3128:28"
  volumes:
   - /opt/glytoucan/squid/log:/var/log/squid3
   - /opt/glytoucan/squid/cache:/var/spool/squid3
   - /etc/localtime:/etc/localtime
  links:
   - java:rdf.glytoucan.org
  restart: always
java:
  # https://github.com/glytoucan/docker-rdf.glytoucan.git
  build: docker-rdf.glytoucan
  ports:
   - 81:80
  volumes:
   - /opt/rdf.glytoucan.org/tmp:/tmp
   - /opt/rdf.glytoucan.org/maven:/root/.m2
   - ./rdf.glytoucan:/workspace
   - /opt/rdf.glytoucan.org/upload:/upload
   - /etc/localtime:/etc/localtime
  working_dir: /workspace
  #env_file: glytoucan.env
  environment:
   - GOOGLE_OAUTH2_CLIENTID
   - GOOGLE_OAUTH2_CLIENTSECRET
   - SPRING_MAIL_USERNAME
   - SPRING_MAIL_PASSWORD
   - SPRING_TRIPLESTORE_PASSWORD
   - SPRING_TRIPLESTORE_URL
   - API_CONTRIBUTOR_ID
   - API_KEY
   - HOSTNAME=${RDF_GLYTOUCAN}
  links:
    - stanza:stanza.glytoucan.org
    - api:test.api.glytoucan.org
    - virtuoso:test.ts.glytoucan.org
#    - local:local.glytoucan.org
  restart: always
stanza:
  build: docker-stanza
  ports:
    - 9292:80
  volumes: 
  # the dockerfile uses /app/glytoucan-stanza so glytoucan-stanza should be in workspace
    - .:/app
    - /etc/localtime:/etc/localtime
  links:
    - api:rdf.glytoucan.org
    - virtuoso:test.ts.glytoucan.org
  restart: always
#user_virtuoso:
#  build: ${WORKSPACE_PARENT}/${WORKSPACE}/docker-virtuoso
#  ports:
#    - 1110:1111
#    - 8889:8890
#  volumes:
#    - /etc/localtime:/etc/localtime
#    - /opt/virtuoso_user:/virtuoso
#  restart: always
api:
  image: maven:3.3.3-jdk-8
  ports:
    - 881:80
  volumes:
    - /opt/api.glytoucan/maven:/root/.m2
    - ./api:/workspace
    - /etc/localtime:/etc/localtime
  working_dir: /workspace
  command: mvn -U spring-boot:run
  environment:
   - SERVER_PORT
   - MAIL_ADDRESS_FROM
   - MAIL_ADDRESS_ADMIN
   - MAIL_BODY_NEWREGISTRATION
   - MAIL_BODY_NOTIFYREGISTRATION
   - MAIL_SUBJECT_NEWREGISTRATION
   - MAIL_SUBJECT_NOTIFYREGISTRATION
   - MSDB_RDF
   - SPRING_MAIL_USERNAME
   - SPRING_MAIL_PASSWORD
   - SPRING_TRIPLESTORE_PASSWORD
   - SPRING_TRIPLESTORE_URL
  restart: always
#awstats:
#  build: ${WORKSPACE_PARENT}/${WORKSPACE}/docker-awstats
#  ports:
#    - "100:80"
#  volumes:
#   - /opt/bluetree/apacherun:/var/run/apache2
#    - /opt/glytoucan/awstats/data:/var/lib/awstats
#    - /opt/glytoucan/apache/www:/var/www/html
#    - /opt/glytoucan/awstats/logs:/var/log
#   - /var/log:/var/log
#   - ${HOME}/${WORKSPACE}/docker-awstats/logs:/var/log/apache2
#    - /etc/localtime:/etc/localtime         
soap.api:
  extends:
    file: soap.api/docker-compose.yml
    service: soap.api
client:
  image: maven:3.3.3-jdk-8
  volumes:
    - /opt/api.glytoucan/maven:/root/.m2
    - ./client:/workspace
    - /etc/localtime:/etc/localtime
  working_dir: /workspace
  command: mvn -U test
  links:
    - api:test.api.glytoucan.org
# https://github.com/aokinobu/docker-virtuoso.git
virtuoso:
  extends:
    file: docker-virtuoso/docker-compose.yml
    service: virtuoso
