version: '2'
services:
  java:
    extends:
      file: docker-compose.java.yml
      service: java
    image: maven:3.3.9-jdk-8
    command: mvn -DskipTests=true clean package
    restart: never
  api:
    extends:
      file: docker-compose.api.yml
      service: api
    image: maven:3.3.9-jdk-8
    command: mvn -DskipTests=true clean package
    restart: never
  soap.api:
    extends:
      file: docker-compose.soap.api.yml
      service: soap.api
    image: maven:3.3.9-jdk-8
    command: mvn -DskipTests=true clean package
    restart: never
