version: '2'
services:
  java:
# https://github.com/glytoucan/docker-rdf.glytoucan.git
    build: docker-rdf.glytoucan
#    image: glytoucan_java:v${GTC_VERSION}
    ports:
     - 81:80
    volumes:
     - ${HOME}/glytoucan/java/tmp:/tmp
     - ${HOME}/glytoucan/maven:/root/.m2
     - ${HOME}/glytoucan/java/upload:/upload
     - /etc/localtime:/etc/localtime
     - ./rdf.glytoucan:/workspace/rdf.glytoucan
#     - source:/workspace
    working_dir: /workspace/rdf.glytoucan
#env_file: glytoucan.env
    environment:
     - HOSTNAME=rdf.glytoucan
#  links:
#    - stanza:stanza.glytoucan.org
#    - api:test.api.glytoucan.org
#    - local:local.glytoucan.org
    restart: always
#volumes:
#  source:
#    external:
#      name: source.${GTC_VERSION}
