version: '2'
services:
  web:
    # https://bitbucket.org/aokinobu/docker-glytoucan.git
    build: docker-glytoucan
#    image: glytoucan_web:v${GTC_VERSION}
    ports:
     - "90:80"
    volumes:
     - /opt/glytoucan/apachelogs:/var/log/apache2
     - /etc/localtime:/etc/localtime
    restart: always
