#!/bin/sh
. ./triplestore.env
. ./user.triplestore.env
. ./google.env
echo GOOGLE_OAUTH2_CLIENTID=$GOOGLE_OAUTH2_CLIENTID GOOGLE_OAUTH2_CLIENTSECRET=$GOOGLE_OAUTH2_CLIENTSECRET SPRING_TRIPLESTORE_URL=$SPRING_TRIPLESTORE_URL SPRING_TRIPLESTORE_PASSWORD=$SPRING_TRIPLESTORE_PASSWORD docker-compose up
GOOGLE_OAUTH2_CLIENTID=$GOOGLE_OAUTH2_CLIENTID GOOGLE_OAUTH2_CLIENTSECRET=$GOOGLE_OAUTH2_CLIENTSECRET SPRING_TRIPLESTORE_URL=$SPRING_TRIPLESTORE_URL SPRING_TRIPLESTORE_PASSWORD=$SPRING_TRIPLESTORE_PASSWORD docker-compose up
