version: '2'
services:
  soap.api:
    image: maven:3.3.3-jdk-8
    ports:
      - 8888:80
    volumes:
      - /opt/maven/m2:/root/.m2
      - ./api.soap:/workspace/soap.api
      - ../pom-site:/workspace/pom-site
      - /etc/localtime:/etc/localtime
    working_dir: /workspace/soap.api
    command: mvn -U clean spring-boot:run
    environment:
     - SERVER_PORT
     - MAIL_ADDRESS_FROM
     - MAIL_ADDRESS_ADMIN
     - MAIL_BODY_NEWREGISTRATION
     - MAIL_BODY_NOTIFYREGISTRATION
     - MAIL_SUBJECT_NEWREGISTRATION
     - MAIL_SUBJECT_NOTIFYREGISTRATION
     - SPRING_MAIL_USERNAME
     - SPRING_MAIL_PASSWORD
     - SPRING_TRIPLESTORE_PASSWORD
     - SPRING_TRIPLESTORE_URL
    restart: always
