soap.api:
  image: maven:3.3.3-jdk-8
  ports:
    - 8881:80
  volumes:
    - /opt/api.glytoucan/maven:/root/.m2
    - ${WORKSPACE_PARENT}/${WORKSPACE_LOCAL}/${SOAP_API_GLYTOUCAN}:/workspace
    - /etc/localtime:/etc/localtime
  working_dir: /workspace
  command: mvn -U spring-boot:run
  environment:
   - SERVER_PORT
   - MAIL_ADDRESS_FROM
   - MAIL_ADDRESS_ADMIN
   - MAIL_BODY_NEWREGISTRATION
   - MAIL_BODY_NOTIFYREGISTRATION
   - MAIL_SUBJECT_NEWREGISTRATION
   - MAIL_SUBJECT_NOTIFYREGISTRATION
   - SPRING_MAIL_USERNAME
   - SPRING_MAIL_PASSWORD
   - SPRING_TRIPLESTORE_PASSWORD
   - SPRING_TRIPLESTORE_URL
  restart: always

